import Head from 'next/head'
import Sidbar from '../components/Sldbar'
import Container from '../components/Container'

export default function Home() {
  return (
    <div >
      
      <Head>
        <title>وب سایت شخصی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main dir='rtl'  >
        <div className='flex flex-1 fixed w-52 clear-left top-0 right-0 '>   
          <Sidbar/>
</div>
        <div className='mr-52  '>   
              <Container/>
</div>
        
        
         

        
    
      
        
      </main>

      <footer >
       
      </footer>
    </div>
  )
}
