import Head from 'next/head'
import Sidbar from '../components/Sldbar'
import Container from '../components/Container'

export default function Home() {
  return (
    <div >
      
      <Head>
        <title>وب سایت شخصی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main dir='rtl'  className="flex flex-row">
        
        <Sidbar/>
        
         
         <Container/>

        
    
      
        
      </main>

      <footer >
       
      </footer>
    </div>
  )
}
